name: Trigger Jenkins on Push

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    
    env:
      JENKINS_URL: "http://192.168.43.236:8081"
      JENKINS_JOB_NAME: "html-static-deploy"

    steps:
      - name: Trigger Jenkins Build
        env:
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
          JENKINS_JOB_TOKEN: ${{ secrets.JENKINS_JOB_TOKEN }}
        run: |
          # Add error handling and verification
          response=$(curl -s -w "%{http_code}" -X POST \
            "${JENKINS_URL}/job/${JENKINS_JOB_NAME}/build?token=${JENKINS_JOB_TOKEN}" \
            --user "${JENKINS_USER}:${JENKINS_API_TOKEN}")
          
          http_code=${response: -3}
          
          if [ "$http_code" -eq 201 ] || [ "$http_code" -eq 200 ]; then
            echo "Jenkins job triggered successfully"
          else
            echo "Failed to trigger Jenkins job. HTTP code: $http_code"
            exit 1
          fi

      - name: Check Build Status
        env:
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
        run: |
          echo "Waiting for build to start..."
          sleep 10
          
          build_status=$(curl -s \
            "${JENKINS_URL}/job/${JENKINS_JOB_NAME}/lastBuild/api/json" \
            --user "${JENKINS_USER}:${JENKINS_API_TOKEN}" | \
            jq -r '.result')
          
          echo "Build status: $build_status"